### ISSUE TITLE
adding special call to action row is still pending

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#99]
@tfsojon 
In one of the videos I asked for this section. 
I want it in a way that it is available for every page, and I want to disable or enable to show only when we are ready to show this call to action row in a page. 
Please let me know what assets you need from me to get this done. For all the project pages, we made dedicated images and gave different colors on every page. We want to be able to do the same for this call-to-action row wherever we put it. 
![image](https://user-images.githubusercontent.com/59978378/233243171-0f400123-9a51-4506-8f39-06d0a7499140.png)

**Comment by sojonatgithub** [comment]
I told this to you 2 weeks ago - https://github.com/intelops/website/issues/56#issuecomment-1497085733

**Comment by devopstoday11** [comment]
@tfsojon , fetching the asset now. I will place them in the chandu branch in assets folder and then I will ping you here.

**Comment by devopstoday11** [comment]
here is the asset located for compage page , @tfsojon 

https://github.com/intelops/website/tree/chandu/assets/images/call-to-actions

**Comment by devopstoday11** [comment]
@tfsojon ,  After you done adding that special call to action thing for Compage page, let me know to test it in my local. If everything looks good, you can provide me steps  on how to add it for other pages and I will do it. 
@sojonatgithub

**Comment by sojonatgithub** [comment]
added in this commit https://github.com/intelops/website/pull/106/commits/b2271a966162f22003e1ae2381007049800119fb

**Comment by devopstoday11** [comment]
> added in this commit [b2271a9](https://github.com/intelops/website/commit/b2271a966162f22003e1ae2381007049800119fb)

@sojonatgithub @tfsojon 
please check this comment on your PR - 
https://github.com/intelops/website/pull/106#issuecomment-1518038887 

This is the video I shared in that comment; just sharing the same in this message as well, 
https://www.loom.com/share/4e83d70a53f64bdeaf689c8f2354b692

**Comment by devopstoday11** [comment]
@sojonatgithub @tfsojon @tfsomrat 
please check above feedback

**Comment by devopstoday11** [comment]
@tfsojon 
added feedback on call-to-action thing - 
https://www.loom.com/share/c8bf41d48821469682c01f8acea8a23b

This video is related to this commit ,
https://github.com/intelops/website/pull/138/commits/07efabf1c50f1b75c936dd9dc165e00dbcc3cd45

**Comment by tfsojon** [comment]
@devopstoday11 
Yes, you can change the text, text-color, bg-color, image using this Param in every page. _**[please save this comment]**_
**[please try exploring this for better understanding]**
```
call_to_action:
  enable: true
  title: "Start using <br/> Compage <br/> platform today..."
  title_color: "#fff"
  subtitle: ""
  subtitle_color: ""
  image: "images/call-to-actions/compage/robo-image.svg"
  button_label: "Get Started"
  button_link: "contact/"
  bg_color: "#005DFF"
  bottom_bg_color: "#080338"
```

Footer has this options in every page
```
footer:
  footer_light: false
  bg_color: "red"
  bg_image: "images/contact-image1.jpg"
  bg_image_overlay_color: "rgba(0,0,0,.85)"
```
![image](https://user-images.githubusercontent.com/87603786/235409327-5325c202-4f75-4f76-8a1c-075bc2242d29.png)


------------

- Added Call to action in blog page footer
- Call to action(CTA) not showing in `certified` page because there no `certified.md` file _[page not found there]_
- Will add The same CTA in doc site.

------------

## Image alignment in platform and open-source pages are bottom-right aligned.
because the CTA was designed like that way. those are different. On other pages the image-alignment is ok.
![image](https://user-images.githubusercontent.com/87603786/235407498-a9f55c08-8ee6-43e8-af13-91fbc4945459.png)
![image](https://user-images.githubusercontent.com/87603786/235407548-d615ee83-be09-46ab-8b1b-caaf486c888f.png)
